[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "a58f94b73c77fd9b3c0326e41324ac13335364cd"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "b8cac0892b8e5f5e06e07ccb54e7721bd5152ab7c5e0c3748f14fb60e7e04a97"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.1+0/libmousetrap.v0.4.1.x86_64-w64-mingw32.tar.gz"
