[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "c13984820b582f1e54190bcd1939dc6593a33992"
julia_version = "1.10.0"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "3d0d464e13a84ec21d57c610efd120649999bd037a0ff2dd15619fb345e78f1d"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.1+0/libmousetrap.v0.4.1.x86_64-w64-mingw32-julia_version+1.10.0.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "7ff3422ceec934daa2f68dd09915c3fd72fe1ec3"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "49953e8212dcf88f35115871af436bf654ef2cbcd2c759d1b2ddadf4e766dbbb"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.2+0/libmousetrap.v0.4.2.x86_64-w64-mingw32.tar.gz"
