[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "c13984820b582f1e54190bcd1939dc6593a33992"
julia_version = "1.10.0"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "3d0d464e13a84ec21d57c610efd120649999bd037a0ff2dd15619fb345e78f1d"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.1+0/libmousetrap.v0.4.1.x86_64-w64-mingw32-julia_version+1.10.0.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "a3b78943e4a2b4a289dd9db8ceebee445ee81f6c"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "7709a7ebcfde530e12f97841c549a7340bafd45920cef56f7c40d3a55650a899"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.2+0/libmousetrap.v0.4.2.x86_64-w64-mingw32.tar.gz"
