[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "f7426e702fa21550b29648b183356f0a427a0ec5"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "985e17341eb59ce09e514180a1df50eb5173c7fe308fe1578a5c66b47d6efef6"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.2+0/libmousetrap.v0.4.2.x86_64-w64-mingw32.tar.gz"
