# Autogenerated wrapper script for mousetrap_windows_jll for x86_64-w64-mingw32
export mousetrap, mousetrap_julia_binding

using GLEW_jll
using GTK4_jll
using OpenGLMathematics_jll
using libcxxwrap_julia_jll
using libadwaita_jll
JLLWrappers.@generate_wrapper_header("mousetrap_windows")
JLLWrappers.@declare_library_product(mousetrap, "libmousetrap.dll")
JLLWrappers.@declare_library_product(mousetrap_julia_binding, "libmousetrap_julia_binding.dll")
function __init__()
    JLLWrappers.@generate_init_header(GLEW_jll, GTK4_jll, OpenGLMathematics_jll, libcxxwrap_julia_jll, libadwaita_jll)
    JLLWrappers.@init_library_product(
        mousetrap,
        "bin\\libmousetrap.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        mousetrap_julia_binding,
        "bin\\libmousetrap_julia_binding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
